name: WebKitBrowser
options:
  bundleIdPrefix: com.noctusoft
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "14.0"
  indentWidth: 4
  tabWidth: 4
  usesTabs: false

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
    DEVELOPMENT_TEAM: "" # Will be set automatically
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"  # For debugging
    SWIFT_COMPILATION_MODE: singlefile  # For debugging
    OTHER_SWIFT_FLAGS: "-D DEBUG"       # For debugging
    SWIFT_TREAT_WARNINGS_AS_ERRORS: NO  # Don't treat warnings as errors during development

schemes:
  WebKitBrowser:
    build:
      targets:
        WebKitBrowser: all
        WebKitBrowserTests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: OS_ACTIVITY_MODE
          value: disable
          isEnabled: true
    test:
      config: Debug
      targets:
        - WebKitBrowserTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  WebKitBrowser:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
      - path: Resources
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Resources/LaunchScreen.storyboard
      - path: Resources/Main.storyboard
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.noctusoft.webkitbrowser
        TARGETED_DEVICE_FAMILY: 1,2 # Universal app
        SUPPORTS_MACCATALYST: NO
        PROVISIONING_PROFILE_SPECIFIER: "" # Will be managed automatically
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_BITCODE: NO
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
        GCC_OPTIMIZATION_LEVEL: 0
        CLANG_ENABLE_MODULES: YES
        CLANG_ENABLE_OBJC_ARC: YES
        VALID_ARCHS: arm64 arm64e x86_64 # Support both simulator and device
        ARCHS: $(ARCHS_STANDARD)
        ONLY_ACTIVE_ARCH: YES # Set to YES for debug builds
        OTHER_LDFLAGS: $(inherited)
        SWIFT_WHOLE_MODULE_OPTIMIZATION: NO
        ENABLE_TESTABILITY: YES
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: WebKit Browser
        CFBundleDisplayName: WebKit Browser
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIViewControllerBasedStatusBarAppearance: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneStoryboardFile: Main
  
  WebKitBrowserTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: WebKitBrowser
    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.noctusoft.webkitbrowser.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/WebKitBrowser.app/WebKitBrowser"
        BUNDLE_LOADER: "$(TEST_HOST)"
